version: '3.8'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - '9100:9100'
    restart: always
    volumes:
      - '/:/host:ro,rslave'
