- name: setup 2GB swapfile for all servers
  hosts: all
  become: yes
  vars:
    swap_file_path: /swapfile
    swap_file_size_mb: 2000
  tasks:
    - name: Create swap file
      command:
        dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}
        creates="{{ swap_file_path }}"
      tags:
        - swap.file.create

    - name: Change swap file permissions
      file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600
      tags:
        - swap.file.permissions

    - name: "Check swap file type"
      command: file {{ swap_file_path }}
      register: swapfile
      tags:
        - swap.file.mkswap

    - name: Make swap file
      command: "sudo mkswap {{ swap_file_path }}"
      when: swapfile.stdout.find('swap file') == -1
      tags:
        - swap.file.mkswap

    - name: Write swap entry in fstab
      mount: name=none
        src={{ swap_file_path }}
        fstype=swap
        opts=sw
        passno=0
        dump=0
        state=present
      tags:
        - swap.fstab

    - name: Mount swap
      command: "swapon {{ swap_file_path }}"
      when: ansible_swaptotal_mb < 1
      tags:
        - swap.file.swapon

- name: install packages for all servers
  hosts: all
  become: yes
  tasks:
    - name: enable nginx in amazon-linux-extras
      shell: amazon-linux-extras enable nginx1
      args:
        creates: /etc/nginx
    - name: install list of packages
      yum:
        name:
          - nginx
          - docker
          - git
        state: latest

- name: install pnpm for cicd servers
  hosts: cicd
  become: yes
  tasks:
    - name: install c compilers
      yum:
        name:
          - gcc-c++
          - make
        state: latest
    - name: get nvm
      shell: curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
    - name: install node
      yum:
        name: nodejs
        state: latest
    - name: install pnpm
      community.general.npm:
        name: pnpm
        global: true
        state: latest

- name: install and setup jenkins on cicd servers
  hosts: cicd
  become: yes
  tasks:
    - name: add jenkins repo
      shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
      args:
        creates: /etc/yum/repos.d/jenkins.repo
    - name: import key file from jenkins-ci to make installable
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present
    - name: install java 11
      shell: amazon-linux-extras install java-openjdk11 -y
      args:
        creates: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
    - name: install jenkins
      yum:
        name:
          - jenkins
        state: latest
    - name: enable and start jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started
