- name: Setup 2GB swapfile for all servers
  hosts: all
  become: true
  vars:
    swap_file_path: /swapfile
    swap_file_size_mb: 2000
  tasks:
    - name: Create swap file
      command:
        dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}
        creates="{{ swap_file_path }}"
      tags:
        - swap.file.create

    - name: Change swap file permissions
      file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600
      tags:
        - swap.file.permissions

    - name: "Check swap file type"
      command: file {{ swap_file_path }}
      register: swapfile
      tags:
        - swap.file.mkswap
      changed_when: false

    - name: Make swap file
      command: "mkswap {{ swap_file_path }}"
      when: swapfile.stdout.find('swap file') == -1
      tags:
        - swap.file.mkswap

    - name: Write swap entry in fstab
      ansible.posix.mount: name=none
        src={{ swap_file_path }}
        fstype=swap
        opts=sw
        passno=0
        dump=0
        state=present
      tags:
        - swap.fstab

    - name: Mount swap
      command: "swapon {{ swap_file_path }}"
      when: ansible_swaptotal_mb < 1
      tags:
        - swap.file.swapon

- name: Install packages for all servers
  hosts: all
  become: true
  tasks:
    - name: Enable nginx in amazon-linux-extras
      command: amazon-linux-extras enable nginx1
      args:
        creates: /etc/nginx
    - name: Install list of packages
      yum:
        name:
          - nginx
          - docker
          - git
        state: present

- name: Install pnpm for cicd servers
  hosts: cicd
  become: true
  tasks:
    - name: Install c compilers
      yum:
        name:
          - gcc-c++
          - make
        state: present
    - name: Get nvm
      ansible.builtin.get_url:
        url: https://rpm.nodesource.com/setup_16.x
        dest: ~/nvm-install.sh
        mode: "600"
    - name: Install nvm
      command: bash ~/nvm-install.sh
      changed_when: false
    - name: Install node
      yum:
        name: nodejs
        state: present
    - name: Install pnpm
      community.general.npm:
        name: pnpm
        global: true
        state: present

- name: Install and setup jenkins on cicd servers
  hosts: cicd
  become: true
  tasks:
    - name: Add jenkins repo
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: "777"
    - name: Import key file from jenkins-ci to make installable
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present
    - name: Install java 11
      command: amazon-linux-extras install java-openjdk11 -y
      args:
        creates: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
    - name: Install jenkins
      yum:
        name:
          - jenkins
        state: present
    - name: Enable and start jenkins service
      systemd:
        name: jenkins
        enabled: true
        state: started
